
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 05 16:17:52 CST 2024
//----------------------------------------------------

package fes.aragon.compilador.cup;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int PUNTO_COMA = 7;
  public static final int ERROR = 10;
  public static final int INICIO = 3;
  public static final int EOF = 0;
  public static final int MOVIMIENTO = 9;
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int PARENTESIS_C = 6;
  public static final int MOVER = 8;
  public static final int PARENTESIS_A = 5;
  public static final int FINAL = 4;
}

